services:
  postgres:
    container_name: umi-postgres-sql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: umi_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - umi-networks
    restart: unless-stopped
    
  recommendation:
    build:
      context: ./recommendation
      dockerfile: Dockerfile
    environment:
      - PORT=5002
      - MODEL_PATH=models/clustering_model.pkl
    volumes:
      - ./recommendation/models:/app/models
    ports:
      - 5002:5002
    networks:
      - umi-networks
    depends_on:
      - postgres
    restart: unless-stopped
    command: gunicorn app:app --bind 0.0.0.0:5002

networks:
  umi-networks:
    driver: bridge

volumes:
  postgres:
    driver: local
