export const pricingOptions = [
  {
    isMostPopular: false,
    header: "RM 0.00, Always",
    type: "Basic",
    target: "Solo Learner",
    price: "Free",
    features: [
      "24/7 Ticket Support System",
      "Unlimited resource access",
      "3 Study groups",
      "5 AI Summarizer",
    ],
    joinQuote: "Sign Up For Free",
  },
  {
    isMostPopular: true,
    header: "RM 0.00 for your first month",
    type: "Premium",
    target: "Advanced Learner",
    price: "RM 50 / mo",
    features: [
      "24/7 Ticket Support System",
      "Unlimited resource access",
      "5 Study groups",
      "10 AI Summarizer",
      "Offline library for pre-downloaded resources",
    ],
    joinQuote: "Start Free Trial",
  },
  {
    isMostPopular: false,
    header: "RM 100.00 for the first three months",
    type: "Plus",
    target: "Education Institution",
    price: "RM 300 / mo",
    features: ["Internal resource library", "Up to 10,000 learners"],
    joinQuote: "Join now for RM 100",
  },
];